name: GitHub Actions Demo
run-name: ${{ github.actor }} estÃ¡ probando GitHub Actions ğŸš€
on: [push]
jobs:
  Explorar-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸš€ El job se activÃ³ automÃ¡ticamente por un evento push."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ El repositorio ha sido clonado en el servidor."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ El estado de este job es ${{ job.status }}."
